docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - Intro: intro.md
    - "Querying HTML and XML": query.md
site_name: zend-dom
site_description: zend-dom
repo_url: 'https://github.com/zendframework/zend-dom'
copyright: 'Copyright (c) 2016 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
